server.port: 8761

# TODO remove
management.security.enabled: false

# standalone mode
eureka:
#  instance:
#    hostname: localhost
#    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  serviceUrl:
    defaultZone: http://localhost:8761

# logging
logging.level:
  com.netflix: WARN
  org.springframework.web: WARN
  com.kdzido.thesis.eureka: DEBUG