server.port: 8761

# logging
logging.level:
  com.netflix: WARN
  org.springframework.web: WARN
  com.kdzido.thesis.eureka: DEBUG

# Eureka peer-aware mode
eureka:
  instance:
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://eurekapeer1:8761/eureka/,http://eurekapeer2:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: eurekapeer1

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: eurekapeer2

