server.port: 8761

# logging
logging.level:
  com.netflix: WARN
  org.springframework.web: WARN
  com.kdzido.thesis.eureka: DEBUG

# Eureka peer-aware mode
eureka:
  instance:
    preferIpAddress: true
  server:
    waitTimeInMsWhenSyncEmpty: 0

---
# cluster mode
spring:
  profiles: peer1
eureka:
  instance:
      # TODO hostName?
    hostname: eurekapeer1
#    ip-address: $$DOCKER_IP
  client:
    serviceUrl:
      defaultZone: http://eurekapeer1:8761/eureka/,http://eurekapeer2:8761/eureka/

---
# cluster mode
spring:
  profiles: peer2
eureka:
  instance:
    # TODO hostName?
    hostname: eurekapeer2
#    ip-address: $$DOCKER_IP
  client:
    serviceUrl:
      defaultZone: http://eurekapeer1:8761/eureka/,http://eurekapeer2:8761/eureka/

#---
## standalone mode
#spring:
#  profiles: standalone
#eureka:
##  instance:
##    hostname: localhost
##    preferIpAddress: true
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
