version: '3'

services:
# Commit
  unit:
    image: openjdk:8u162-jdk
    volumes:
      - .:/appsrc
      - ./rootGradle:/root/.gradle
    working_dir: /appsrc
    command: bash -c "./gradlew clean build copyDockerFiles"

  app:
    build:
      context: ./backend-eureka-service/build/dockerfile/
    image: thesis-eurekaservice:snapshot

# Staging
  eurekapeer1:
    image: thesis-eurekaservice:snapshot
    environment:
      PROFILE: "peer1"
    ports:
      - "8761:8761"

  eurekapeer2:
    image: thesis-eurekaservice:snapshot
    environment:
      PROFILE: "peer2"
    ports:
      - "8762:8761"

  staging:
    image: openjdk:8u162-jdk
    volumes:
      - .:/appsrc
      - ./rootGradle:/root/.gradle
    environment:
      - EUREKAPEER_1 = eurekapeer1
      - EUREKAPEER_2 = eurekapeer2
    working_dir: /appsrc
    command: bash -c "./gradlew integTest"
