version: '2'

services:
# Commit
  unit:
    image: openjdk:8u162-jdk
    volumes:
      - .:/appsrc
      - ./rootGradle:/root/.gradle
    working_dir: /appsrc
    command: bash -c "./gradlew clean build copyDockerFiles --no-daemon"

  app:
    build:
      context: ./backend-eureka-service/build/dockerfile/
    image: thesis-eurekaservice:snapshot

# Staging
# TODO make hostnames (eurekapeer1, eurekapeer2) parametrizable
  eurekapeer1:
    image: thesis-eurekaservice:snapshot
    mem_limit: 500m   # jvm allocates 1/4 to max heap size
    environment:
      - PROFILE=peer1
    ports:
      - "7761:8761"

  eurekapeer2:
    image: thesis-eurekaservice:snapshot
    mem_limit: 500m   # jvm allocates 1/4 to max heap size
    environment:
      - PROFILE=peer2
    ports:
      - "7762:8761"

  staging:
#    image: openjdk:8u162-jdk
    image: fabric8/java-jboss-openjdk8-jdk:1.4.0
#    mem_limit: 1570m  # jboss jdk allocates 1/2 to max heap size
    depends_on:
      - eurekapeer1
      - eurekapeer2
    volumes:
      - .:/appsrc
      - ./rootGradle:/root/.gradle
    environment:
      - EUREKASERVICE_URI_1=http://eurekapeer1:8761
      - EUREKASERVICE_URI_2=http://eurekapeer2:8761
    working_dir: /appsrc
    command: bash -c "ping -c 1 eurekapeer1 && ping -c 1 eurekapeer2 && ./gradlew integTest --no-daemon"
